// 渲染風格：參數表（調整介面的滑桿依這裡產生）、內建預設、正規化
// 參數是扁平物件；顏色一律 '#rrggbb'（sRGB），套用時再轉線性。內建預設「寫實」等於原本的畫面。

// t：num 滑桿／int 整數滑桿／sel 下拉選單／color 顏色／bool 開關；when(P) 為 false 時調整介面隱藏該項
export const STYLE_GROUPS = [
  {
    id: 'shade',
    name: '著色',
    items: [
      {
        k: 'toon',
        t: 'sel',
        label: '光照模式',
        opts: [
          [0, '物理（寫實）'],
          [1, '色階（賽璐璐）'],
        ],
      },
      { k: 'steps', t: 'int', label: '色階數', min: 2, max: 4, when: (P) => P.toon },
      { k: 'thresh', t: 'num', label: '明暗分界', min: 0.05, max: 0.95, step: 0.01, when: (P) => P.toon },
      { k: 'soft', t: 'num', label: '交界柔和度', min: 0, max: 0.25, step: 0.005, when: (P) => P.toon },
      { k: 'shade', t: 'color', label: '影色', when: (P) => P.toon },
      { k: 'shadeK', t: 'num', label: '暗面亮度', min: 0, max: 1.5, step: 0.01, when: (P) => P.toon },
      { k: 'litK', t: 'num', label: '亮面亮度', min: 0.4, max: 2, step: 0.01, when: (P) => P.toon },
      { k: 'ambient', t: 'num', label: '環境光混入', min: 0, max: 1.5, step: 0.01, when: (P) => P.toon },
      { k: 'spec', t: 'num', label: '高光強度', min: 0, max: 2, step: 0.01, when: (P) => P.toon },
      { k: 'specSize', t: 'num', label: '高光大小', min: 0, max: 1, step: 0.01, when: (P) => P.toon },
      { k: 'specSoft', t: 'num', label: '高光邊緣柔和', min: 0, max: 0.3, step: 0.005, when: (P) => P.toon },
      { k: 'rim', t: 'num', label: '邊緣光強度', min: 0, max: 2, step: 0.01, when: (P) => P.toon },
      { k: 'rimW', t: 'num', label: '邊緣光寬度', min: 0.02, max: 0.8, step: 0.01, when: (P) => P.toon },
      { k: 'rimColor', t: 'color', label: '邊緣光顏色', when: (P) => P.toon },
      { k: 'mechDetail', t: 'num', label: '機體貼圖細節', min: 0, max: 1, step: 0.01 },
      { k: 'envDetail', t: 'num', label: '地形貼圖細節', min: 0, max: 1, step: 0.01 },
      { k: 'normalK', t: 'num', label: '面板凹凸強度', min: 0, max: 2, step: 0.01 },
      { k: 'envRefl', t: 'num', label: '環境反射強度', min: 0, max: 3, step: 0.01, when: (P) => !P.toon },
    ],
  },
  {
    id: 'metal',
    name: '機體材質（機甲、武器、載具）',
    items: [
      { k: 'metal', t: 'bool', label: '金屬' },
      { k: 'metalness', t: 'num', label: '金屬感', min: 0, max: 1, step: 0.01, when: (P) => P.metal },
      { k: 'roughness', t: 'num', label: '粗糙度', min: 0.04, max: 1, step: 0.01, when: (P) => P.metal },
      { k: 'metalTint', t: 'num', label: '保留陣營色', min: 0, max: 1, step: 0.01, when: (P) => P.metal },
      {
        k: 'metalRefl',
        t: 'num',
        label: '反射強度',
        min: 0,
        max: 4,
        step: 0.01,
        when: (P) => P.metal && !P.toon,
      },
      {
        k: 'metalAnime',
        t: 'num',
        label: '動畫金屬反光帶',
        min: 0,
        max: 1,
        step: 0.01,
        when: (P) => P.metal && P.toon,
      },
    ],
  },
  {
    id: 'ink',
    name: '描線',
    items: [
      { k: 'ink', t: 'num', label: '描線強度', min: 0, max: 1, step: 0.01 },
      {
        k: 'inkOuter',
        t: 'num',
        label: '外輪廓粗細（px）',
        min: 0,
        max: 4,
        step: 0.1,
        when: (P) => P.ink > 0,
      },
      { k: 'inkInner', t: 'num', label: '內線粗細（px）', min: 0, max: 3, step: 0.1, when: (P) => P.ink > 0 },
      { k: 'crease', t: 'num', label: '轉折靈敏度', min: 0, max: 1, step: 0.01, when: (P) => P.ink > 0 },
      { k: 'inkColor', t: 'color', label: '線色', when: (P) => P.ink > 0 },
      { k: 'inkObj', t: 'num', label: '線色取物體色', min: 0, max: 1, step: 0.01, when: (P) => P.ink > 0 },
      { k: 'inkNear', t: 'num', label: '開始淡出（m）', min: 5, max: 300, step: 1, when: (P) => P.ink > 0 },
      { k: 'inkFar', t: 'num', label: '完全淡出（m）', min: 10, max: 400, step: 1, when: (P) => P.ink > 0 },
      { k: 'inkEnv', t: 'num', label: '地形描線', min: 0, max: 1, step: 0.01, when: (P) => P.ink > 0 },
      { k: 'hull', t: 'num', label: '外殼描邊（舊）', min: 0, max: 3, step: 0.05 },
    ],
  },
  {
    id: 'light',
    name: '光與陰影',
    items: [
      { k: 'sunAz', t: 'num', label: '太陽方位（°）', min: 0, max: 360, step: 1 },
      { k: 'sunEl', t: 'num', label: '太陽高度（°）', min: 5, max: 89, step: 1 },
      { k: 'sunK', t: 'num', label: '太陽強度', min: 0, max: 3, step: 0.01 },
      { k: 'sunWarm', t: 'num', label: '陽光色溫（冷↔暖）', min: -1, max: 1, step: 0.01 },
      { k: 'hemiK', t: 'num', label: '環境光強度', min: 0, max: 3, step: 0.01 },
      {
        k: 'shadowType',
        t: 'sel',
        label: '陰影邊緣',
        opts: [
          ['soft', '柔和'],
          ['hard', '硬邊'],
        ],
      },
      { k: 'shadowK', t: 'num', label: '陰影濃度', min: 0, max: 1, step: 0.01 },
      {
        k: 'toneMap',
        t: 'sel',
        label: '色調映射',
        opts: [
          ['aces', 'ACES 電影'],
          ['linear', '線性'],
          ['reinhard', 'Reinhard'],
          ['cineon', 'Cineon'],
        ],
      },
      { k: 'exposure', t: 'num', label: '曝光', min: 0.2, max: 2.5, step: 0.01 },
    ],
  },
  {
    id: 'air',
    name: '大氣與天空',
    items: [
      { k: 'fogK', t: 'num', label: '霧的距離', min: 0.3, max: 3, step: 0.01 },
      { k: 'fogColor', t: 'color', label: '霧色' },
      { k: 'fogColorK', t: 'num', label: '霧色混入', min: 0, max: 1, step: 0.01 },
      { k: 'hfog', t: 'num', label: '高度霧濃度', min: 0, max: 1, step: 0.01 },
      {
        k: 'hfogH',
        t: 'num',
        label: '高度霧高度（m）',
        min: -5,
        max: 30,
        step: 0.5,
        when: (P) => P.hfog > 0,
      },
      {
        k: 'hfogFall',
        t: 'num',
        label: '高度霧衰減（m）',
        min: 1,
        max: 40,
        step: 0.5,
        when: (P) => P.hfog > 0,
      },
      { k: 'dust', t: 'num', label: '空氣塵埃', min: 0, max: 1, step: 0.01 },
      {
        k: 'sky',
        t: 'sel',
        label: '天空',
        opts: [
          ['theme', '戰區原色'],
          ['grad', '漸層'],
          ['cloud', '積雲'],
        ],
      },
      { k: 'skyTop', t: 'color', label: '天頂色', when: (P) => P.sky !== 'theme' },
      { k: 'cloud', t: 'num', label: '雲量', min: 0, max: 1, step: 0.01, when: (P) => P.sky === 'cloud' },
      {
        k: 'skyToon',
        t: 'num',
        label: '雲的色階感',
        min: 0,
        max: 1,
        step: 0.01,
        when: (P) => P.sky === 'cloud',
      },
      { k: 'water', t: 'num', label: '水彩地形', min: 0, max: 1, step: 0.01 },
      {
        k: 'waterScale',
        t: 'num',
        label: '水彩筆觸大小',
        min: 0.02,
        max: 0.4,
        step: 0.005,
        when: (P) => P.water > 0,
      },
    ],
  },
  {
    id: 'post',
    name: '後處理',
    items: [
      { k: 'ssao', t: 'num', label: '環境光遮蔽（SSAO）', min: 0, max: 1.5, step: 0.01 },
      { k: 'bloom', t: 'num', label: '光暈強度', min: 0, max: 3, step: 0.01 },
      { k: 'bloomR', t: 'num', label: '光暈半徑', min: 0, max: 1, step: 0.01, when: (P) => P.bloom > 0 },
      { k: 'bloomTh', t: 'num', label: '光暈門檻', min: 0, max: 1, step: 0.01, when: (P) => P.bloom > 0 },
      { k: 'sat', t: 'num', label: '飽和度', min: 0, max: 2, step: 0.01 },
      { k: 'contrast', t: 'num', label: '對比', min: 0.5, max: 1.6, step: 0.01 },
      { k: 'bright', t: 'num', label: '亮度', min: -0.3, max: 0.3, step: 0.005 },
      { k: 'temp', t: 'num', label: '色溫（冷↔暖）', min: -1, max: 1, step: 0.01 },
      { k: 'tintLo', t: 'color', label: '暗部色偏' },
      { k: 'tintLoK', t: 'num', label: '暗部色偏強度', min: 0, max: 1, step: 0.01 },
      { k: 'tintHi', t: 'color', label: '亮部色偏' },
      { k: 'tintHiK', t: 'num', label: '亮部色偏強度', min: 0, max: 1, step: 0.01 },
      { k: 'vignette', t: 'num', label: '暗角', min: 0, max: 1, step: 0.01 },
      { k: 'chroma', t: 'num', label: '色差', min: 0, max: 1, step: 0.01 },
      { k: 'grain', t: 'num', label: '底片顆粒', min: 0, max: 1, step: 0.01 },
      { k: 'paper', t: 'num', label: '紙紋', min: 0, max: 1, step: 0.01 },
      { k: 'mblur', t: 'bool', label: '動態模糊' },
      { k: 'mblurK', t: 'num', label: '模糊強度', min: 0, max: 1, step: 0.01, when: (P) => P.mblur },
      { k: 'mblurMech', t: 'num', label: '機體保持清晰', min: 0, max: 1, step: 0.01, when: (P) => P.mblur },
      { k: 'fxaa', t: 'bool', label: '反鋸齒（FXAA）' },
    ],
  },
];

export const STYLE_ITEMS = {};
for (const g of STYLE_GROUPS) for (const it of g.items) STYLE_ITEMS[it.k] = it;

// 寫實：原本的畫面（曝光 0.68、ACES、SSAO、Bloom 0.45/0.4/0.9、外殼描邊）
const REAL = {
  toon: 0,
  steps: 2,
  thresh: 0.5,
  soft: 0.02,
  shade: '#8d92c8',
  shadeK: 1,
  litK: 1,
  ambient: 0.4,
  spec: 0.6,
  specSize: 0.35,
  specSoft: 0.02,
  rim: 0,
  rimW: 0.25,
  rimColor: '#ffffff',
  mechDetail: 1,
  envDetail: 1,
  normalK: 1,
  envRefl: 1,
  metal: false,
  metalness: 0.9,
  roughness: 0.28,
  metalTint: 0.7,
  metalRefl: 1.6,
  metalAnime: 0.8,
  ink: 0,
  inkOuter: 1.6,
  inkInner: 0.8,
  crease: 0.5,
  inkColor: '#141826',
  inkObj: 0,
  inkNear: 60,
  inkFar: 170,
  inkEnv: 0.5,
  hull: 1,
  sunAz: 37,
  sunEl: 58,
  sunK: 1,
  sunWarm: 0,
  hemiK: 1,
  shadowType: 'soft',
  shadowK: 1,
  toneMap: 'aces',
  exposure: 0.68,
  fogK: 1,
  fogColor: '#9aa8b8',
  fogColorK: 0,
  hfog: 0,
  hfogH: 2,
  hfogFall: 8,
  dust: 0,
  sky: 'theme',
  skyTop: '#3d7fd4',
  cloud: 0.5,
  skyToon: 0,
  water: 0,
  waterScale: 0.08,
  ssao: 1,
  bloom: 0.45,
  bloomR: 0.4,
  bloomTh: 0.9,
  sat: 1,
  contrast: 1,
  bright: 0,
  temp: 0,
  tintLo: '#2f6b78',
  tintLoK: 0,
  tintHi: '#ffb46b',
  tintHiK: 0,
  vignette: 0,
  chroma: 0,
  grain: 0,
  paper: 0,
  mblur: false,
  mblurK: 0.5,
  mblurMech: 0.7,
  fxaa: true,
};
export const STYLE_DEFAULTS = REAL;

// 內建預設：寫實、機戰傭兵 6、2000 年代 Gundam 動畫、宮崎駿／吉卜力、鳥山明 SAND LAND
export const BUILTIN_STYLES = [
  { id: 'real', name: '寫實（原本的畫面）', params: {} },
  {
    id: 'ac6',
    name: '機戰傭兵 6',
    params: {
      mechDetail: 1,
      normalK: 1.25,
      envRefl: 1.2,
      metalness: 0.85,
      roughness: 0.38,
      metalTint: 0.75,
      metalRefl: 1.8,
      hull: 0,
      sunAz: 205,
      sunEl: 24,
      sunK: 1.25,
      sunWarm: 0.45,
      hemiK: 0.8,
      exposure: 0.7,
      fogK: 0.75,
      fogColor: '#b39b7d',
      fogColorK: 0.45,
      hfog: 0.35,
      hfogH: 1,
      hfogFall: 8,
      dust: 0.6,
      ssao: 1.1,
      bloom: 0.9,
      bloomR: 0.55,
      bloomTh: 0.72,
      sat: 0.72,
      contrast: 1.12,
      bright: -0.01,
      temp: 0.08,
      tintLo: '#2f6b78',
      tintLoK: 0.4,
      tintHi: '#ffb46b',
      tintHiK: 0.3,
      vignette: 0.45,
      chroma: 0.25,
      grain: 0.22,
      mblur: true,
      mblurK: 0.5,
      mblurMech: 0.75,
    },
  },
  {
    id: 'gundam',
    name: '2000 年代 Gundam 動畫',
    params: {
      toon: 1,
      steps: 2,
      thresh: 0.52,
      soft: 0.012,
      shade: '#7f85cc',
      shadeK: 1,
      litK: 1.05,
      ambient: 0.3,
      spec: 0.9,
      specSize: 0.35,
      specSoft: 0.015,
      rim: 0.55,
      rimW: 0.2,
      rimColor: '#ffffff',
      mechDetail: 0.12,
      envDetail: 0.35,
      normalK: 0.3,
      metalness: 0.9,
      roughness: 0.2,
      metalTint: 0.8,
      metalAnime: 0.85,
      ink: 1,
      inkOuter: 2,
      inkInner: 1,
      crease: 0.55,
      inkColor: '#141a2e',
      inkObj: 0.15,
      inkNear: 70,
      inkFar: 190,
      inkEnv: 0.45,
      hull: 0,
      sunEl: 55,
      sunK: 1,
      hemiK: 1,
      shadowType: 'hard',
      shadowK: 0.85,
      toneMap: 'linear',
      exposure: 0.92,
      fogK: 1.3,
      sky: 'grad',
      skyTop: '#2f6fd0',
      ssao: 0,
      bloom: 0.4,
      bloomR: 0.25,
      bloomTh: 0.88,
      sat: 1.25,
      contrast: 1.08,
      vignette: 0.1,
    },
  },
  {
    id: 'ghibli',
    name: '宮崎駿／吉卜力',
    params: {
      toon: 1,
      steps: 3,
      thresh: 0.42,
      soft: 0.06,
      shade: '#b08aa6',
      shadeK: 1,
      litK: 1,
      ambient: 0.55,
      spec: 0.15,
      specSize: 0.2,
      specSoft: 0.05,
      rim: 0.25,
      rimW: 0.3,
      rimColor: '#fff2d6',
      mechDetail: 0.3,
      envDetail: 0.5,
      normalK: 0.25,
      metalness: 0.75,
      roughness: 0.35,
      metalTint: 0.85,
      metalAnime: 0.55,
      ink: 0.85,
      inkOuter: 1.2,
      inkInner: 0.7,
      crease: 0.35,
      inkColor: '#3a2c2a',
      inkObj: 0.85,
      inkNear: 30,
      inkFar: 110,
      inkEnv: 0.25,
      hull: 0,
      sunAz: 60,
      sunEl: 50,
      sunK: 1.05,
      sunWarm: 0.3,
      hemiK: 1.15,
      shadowType: 'soft',
      shadowK: 0.55,
      toneMap: 'linear',
      exposure: 0.95,
      fogK: 1.15,
      fogColor: '#cfe3f0',
      fogColorK: 0.5,
      hfog: 0.12,
      hfogH: 0,
      hfogFall: 12,
      sky: 'cloud',
      skyTop: '#4a90d9',
      cloud: 0.6,
      skyToon: 0.5,
      water: 0.8,
      waterScale: 0.08,
      ssao: 0,
      bloom: 0.25,
      bloomR: 0.6,
      bloomTh: 0.85,
      sat: 1.1,
      contrast: 0.92,
      bright: 0.03,
      temp: 0.15,
      tintLo: '#5a4a8a',
      tintLoK: 0.2,
      tintHi: '#fff0c8',
      tintHiK: 0.25,
      vignette: 0.15,
      grain: 0.05,
      paper: 0.45,
    },
  },
  {
    // 鳥山明《SAND LAND》：正午的沙漠強光與硬邊陰影、乾淨的兩階賽璐璐、偏冷的影色對比暖陽、
    // 粗而深的外輪廓、塗裝感（低金屬）的圓潤機械、飽和的藍天與遠方的暖色沙塵
    id: 'sandland',
    name: '鳥山明 SAND LAND',
    params: {
      toon: 1,
      steps: 2,
      thresh: 0.48,
      soft: 0.008,
      shade: '#8c84b8',
      shadeK: 0.95,
      litK: 1,
      ambient: 0.35,
      spec: 0.55,
      specSize: 0.25,
      specSoft: 0.01,
      rim: 0.35,
      rimW: 0.22,
      rimColor: '#fff4e0',
      mechDetail: 0.18,
      envDetail: 0.4,
      normalK: 0.35,
      metalness: 0.45,
      roughness: 0.5,
      metalTint: 0.92,
      metalAnime: 0.45,
      ink: 1,
      inkOuter: 2.4,
      inkInner: 0.9,
      crease: 0.45,
      inkColor: '#1c140e',
      inkObj: 0.2,
      inkNear: 60,
      inkFar: 180,
      inkEnv: 0.4,
      hull: 0,
      sunAz: 150,
      sunEl: 66,
      sunK: 0.95,
      sunWarm: 0.35,
      hemiK: 0.85,
      shadowType: 'hard',
      shadowK: 0.9,
      toneMap: 'linear',
      exposure: 0.74,
      fogK: 1.2,
      fogColor: '#e6cfa2',
      fogColorK: 0.35,
      hfog: 0.15,
      hfogH: 0,
      hfogFall: 10,
      dust: 0.25,
      sky: 'grad',
      skyTop: '#2a86e0',
      ssao: 0,
      bloom: 0.15,
      bloomR: 0.35,
      bloomTh: 0.88,
      sat: 1.22,
      contrast: 1.1,
      bright: -0.01,
      temp: 0.12,
      tintLo: '#6a4a3a',
      tintLoK: 0.15,
      tintHi: '#fff0d0',
      tintHiK: 0.1,
      vignette: 0.05,
    },
  },
];

// 補齊缺少的欄位、修正型別與範圍（讀到舊版或別人上傳的參數時用）
export function normalizeStyle(p) {
  const out = {};
  const src = p && typeof p === 'object' ? p : {};
  for (const k in REAL) {
    const it = STYLE_ITEMS[k];
    let v = src[k];
    const d = REAL[k];
    if (!it) {
      out[k] = d;
      continue;
    }
    if (it.t === 'bool') v = v === undefined ? d : !!v;
    else if (it.t === 'color') v = typeof v === 'string' && /^#[0-9a-f]{6}$/i.test(v) ? v.toLowerCase() : d;
    else if (it.t === 'sel') v = it.opts.some((o) => o[0] === v) ? v : d;
    else {
      v = typeof v === 'number' && isFinite(v) ? Math.min(it.max, Math.max(it.min, v)) : d;
      if (it.t === 'int') v = Math.round(v);
    }
    out[k] = v;
  }
  return out;
}
export function builtinParams(id) {
  const b = BUILTIN_STYLES.find((s) => s.id === id) || BUILTIN_STYLES[0];
  return normalizeStyle(Object.assign({}, REAL, b.params));
}
