// 進入點：載入所有 Game／MechEntity 擴充後建立遊戲實例
import { Game } from './game/game.js';

import './game/render-setup.js';
import './game/save.js';
import './game/input.js';
import './game/settings.js';
import './game/local-lib.js';
import './game/garage.js';
import './game/pilot.js';
import './game/pilot-ui.js';
import './game/mission.js';
import './game/player.js';
import './game/camera.js';
import './game/hud.js';
import './game/mp-lobby.js';
import './game/mp-host.js';
import './game/mp-client.js';
import './entities/mech-remote.js';
import './entities/mech-special.js';
import './entities/mech-boss.js';
import './entities/mech-boss2.js';
import './game/map-extras.js';
import './game/shockwave.js';
import './game/support.js';
import './game/bosses.js';
import './game/bosses2.js';
import './game/first-person.js';
import './game/pvp.js';
import './game/mp-models.js';
import './game/style-lab.js';
import './game/fullscreen.js';
import './game/campaign.js';
import './game/comms.js';
import './game/hub.js';
import './game/tactics.js';
import './game/campaign-mp.js';
import './entities/mech-objective.js';
import './entities/mech-foe.js';
import './game/sim.js';

new Game();
